[global]
pprof = ":6061"

# server
dc = "shenzhen"
name = "islb"
nid = "shenzhen_islb_1"

[etcd]
#addrs = "127.0.0.1:2379"
addrs = ["127.0.0.1:2379"]

[nats]
url = "nats://127.0.0.1:4222"

[redis]
addrs = [":6379"]
password = ""
db = 0
